name: TopLuck
main: me.cocolennon.topluck.Main
version: 1.0.5
author: Cocolennon
api-version: 1.17
softdepend:
  - PlaceholderAPI
commands:
  topluck:
    description: Opens the TopLuck menu
    aliases:
      - tl
permissions:
  topluck.open:
    description: Allows the user to open the Top Luck menu
  topluck.info:
    description: Allows the user to see the plugin's info
  topluck.reload:
    description: Allows the user to reload the configuration
  topluck.invsee:
    description: Allows the user to open someone else's inventory
  topluck.invsee.move:
    description: Allows the user to move items in someone else's inventory
  topluck.warn.public:
    description: Allows the user to warn someone publicly
  topluck.warn.private:
    description: Allows the user to warn someone privately