name: TopLuck
main: me.cocolennon.topluck.Main
version: 1.1.1
author: Cocolennon
api-version: 1.19
commands:
  topluck:
    description: Opens the TopLuck menu
    aliases:
      - tl
permissions:
  topluck.open:
    description: Allows the user to open the Top Luck menu